name: Build and Deploy Static Page

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Download NGSolve Pyodide package
    - name: Download NGSolve Pyodide
      run: |
        wget https://ngsolve.org/files/ngsolve_pyodide_0.26.2.tar.bz2
        tar xvf ngsolve_pyodide_0.26.2.tar.bz2
        rm ngsolve_pyodide_0.26.2.tar.bz2
    
    # Serve static content
    - name: Serve static content
      run: |
        mkdir -p public
        mv *.html pyodide *.wgsl *.py public/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

